(source melpa)

(depends-on "enh-ruby-mode")
(depends-on "magit")
(depends-on "use-package")
(depends-on "smex")

;; Colors
(depends-on "alect-themes")
(depends-on "clues-theme")
(depends-on "subatomic256-theme")