(source melpa)

(depends-on "enh-ruby-mode")
(depends-on "ido")
(depends-on "ido-ubiquitous")
(depends-on "magit")
(depends-on "projectile")
(depends-on "smex")
(depends-on "use-package")
(depends-on "windmove")
(depends-on "yaml-mode")

;; Colors
(depends-on "alect-themes")
(depends-on "clues-theme")
(depends-on "subatomic256-theme")